title: Controlable
description: Intelligent Edge Management
url: https://koenlammers.github.io
baseurl: /Controlable
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude unnecessary files
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Assets
assets:
  sources:
    - _assets

# Build settings
markdown: kramdown
permalink: /:title/
